### ISSUE TITLE
online or offline

### ISSUE THREAD

**Issue by thresh12138** [chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT#11]
Dear author, I would like to ask whether the following method is online or offline

**Comment by chen-si-jia** [comment]
online

------------------ Original ------------------
From: thresh12138 ***@***.***&gt;
Date: Tue,Jun 25,2024 4:02 PM
To: chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT] online oroffline (Issue #11)
