### ISSUE TITLE
Can SVA and DVA modules be used for multi-target tracking algorithms of simple real-time online tracking series?

### ISSUE THREAD

**Issue by yangzhishuai2022** [chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT#12]
First of all, thank you very much for your wonderful sharing. Can SVA and DVA modules be used for multi-target tracking algorithms of simple real-time online tracking series? For example, SORT, DeepSORT and so on

**Comment by chen-si-jia** [comment]
Our SVA and DVA modules are suitable for learnable multi-object tracking algorithms. Thus, they do not apply SORT, but DeepSORT.



发自我的iPhone


------------------ Original ------------------
From: yangzhishuai2022 ***@***.***&gt;
Date: Thu,Jun 27,2024 10:01 AM
To: chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT] Can SVA andDVA modules be used for multi-target tracking algorithms of simple real-timeonline tracking series? (Issue #12)





 
First of all, thank you very much for your wonderful sharing. Can SVA and DVA modules be used for multi-target tracking algorithms of simple real-time online tracking series? For example, SORT, DeepSORT and so on
