### ISSUE TITLE
The DVA module only be applied to train set?

### ISSUE THREAD

**Issue by su809** [chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT#13]
作者您好，请问DVA模块只能应用在train set上吗？DVA模块代码step_1.py和step_3.py中都需要gt.txt，test set并未提供gt.txt, DVA并不能对test set做出处理吗?

**Comment by chen-si-jia** [comment]
是的。当然对于训练集进行处理了，官方测试集是不开放gt的。


------------------ Original ------------------
From: su809 ***@***.***&gt;
Date: Sun,Jul 14,2024 10:42 AM
To: chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT] The DVAmodule only be applied to train set? (Issue #13)





 
作者您好，请问DVA模块只能应用在train set上吗？DVA模块代码step_1.py和step_3.py中都需要gt.txt，test set并未提供gt.txt, DVA并不能对test set做出处理吗?

**Comment by su809** [comment]
那在test set上不能使用DVA这个方法吗？论文中test上的数据是没加DVA方法得到的吗？

**Comment by chen-si-jia** [comment]
是的。test数据是没经过任何处理的。



发自我的iPhone


------------------ Original ------------------
From: su809 ***@***.***&gt;
Date: Sun,Jul 14,2024 11:10 AM
To: chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT ***@***.***&gt;
Cc: 陈思佳 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT] The DVAmodule only be applied to train set? (Issue #13)

**Comment by su809** [comment]
您好 我想问下。如果我想使用DVA模块(在此基础上做出改进)，仅在验证集上做实验，而不在test set上跑数据，这样可行吗？论文中可以这样吗？(论文方面没有经验，想请教下)



---Original---
From: ***@***.***&gt;
Date: Sun, Jul 14, 2024 11:15 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT] The DVAmodule only be applied to train set? (Issue #13)




 是的。test数据是没经过任何处理的。 
 
 
 
 发自我的iPhone 
 
 
 ------------------ Original ------------------ 
 From: su809 ***@***.***&amp;gt; 
 Date: Sun,Jul 14,2024 11:10 AM 
 To: chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT ***@***.***&amp;gt; 
 Cc: 陈思佳 ***@***.***&amp;gt;, Comment ***@***.***&amp;gt; 
 Subject: Re: [chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT] The DVAmodule only be applied to train set? (Issue #13)

**Comment by chen-si-jia** [comment]
DVA只是用于训练集。虽然我们知道验证集的GT，但是“如果使用DVA处理验证集并在验证集测试指标的话，是不公平的”。可以考虑改进DVA模块，也遵从我们的思路：只对训练集进行处理。


------------------ Original ------------------
From: su809 ***@***.***&gt;
Date: Sun,Jul 14,2024 11:23 AM
To: chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT ***@***.***&gt;
Cc: 陈思佳 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT] The DVAmodule only be applied to train set? (Issue #13)

**Comment by su809** [comment]
好的 谢谢
