### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by CyanH1876** [chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT#2]
Hi Authors,

Thank you for your work. We met some problems in your demo.

The line 30 of demo.py doesn't match function eval_seq in track.py.

If we change to line 70 of eval_seq, we don't know what the "seq" is in line 96.

Thanks!

**Comment by chen-si-jia** [comment]
I have modified and updated the demo.py and track.py.

**Comment by CyanH1876** [comment]
work! thanks!
