### ISSUE TITLE
predicted trajectory

### ISSUE THREAD

**Issue by lanheshui** [chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT#3]
Hello author, I have not been exposed to this field before, and I would like to share this paper of yours in class. I don’t quite understand why the predicted trajectory of the pedestrian is added before the original trajectory in the Prediction continuation?Doesn't it make sense intuitively to add the predicted frame after the original frame?

**Comment by chen-si-jia** [comment]
> Hello author, I have not been exposed to this field before, and I would like to share this paper of yours in class. I don’t quite understand why the predicted trajectory of the pedestrian is added before the original trajectory in the Prediction continuation?Doesn't it make sense intuitively to add the predicted frame after the original frame?

Because the Prediction continuation is a pedestrian belonging to the tail class that processes the last frame of the training set, the last frame of the training set has no subsequent frames. Thus, the prediction results are added before the original trajectories of these pedestrians.
