### ISSUE TITLE
train.sh --exp_id 

### ISSUE THREAD

**Issue by Lsyccnu** [chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT#6]
作者您好！我正在尝试学习并复现您的论文，发现在开始训练的时候，训练脚本中有一个参数为--exp_id mot20_add_our_method_correction_dla34/mot20_add_our_method_correction_visualThreshold_1.0/strength_sampling_threshold_1.0_gs_2，这个要怎么得到呢？

**Comment by chen-si-jia** [comment]
> 作者您好！我正在尝试学习并复现您的论文，发现在开始训练的时候，训练脚本中有一个参数为--exp_id mot20_add_our_method_correction_dla34/mot20_add_our_method_correction_visualThreshold_1.0/strength_sampling_threshold_1.0_gs_2，这个要怎么得到呢？

--exp_id 是训练存储的文件夹名称，这个可以名称自己任意定义。

**Comment by Lsyccnu** [comment]
![res](https://github.com/chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT/assets/101462306/b19f556b-612c-43da-ba1e-b79c640c325c)
作者您好，我在MOT_20上训练了baseline+your_models，然后运行MOT20的track.sh，最后的结果全是0，这是正常的,吗？下面是我的MOT20_track.sh
![track](https://github.com/chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT/assets/101462306/50d18077-9e7a-46ef-b891-057cc24ecb86)

**Comment by qiuricaideng** [comment]
同学您好，我是刚刚进入这个领域的新人，很多还不懂，请问我没有label2binlabel.pt、pred_slice_with0.pt 这俩文件，您是怎么开始baseline+your_models版本的呢，要修改哪些地方呢，我修改了好多路径，但还是不能开始训练，如能赐教，不胜感激！
