### ISSUE TITLE
Track failure 

### ISSUE THREAD

**Issue by Lsyccnu** [chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT#7]
![res](https://github.com/chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT/assets/101462306/b19f556b-612c-43da-ba1e-b79c640c325c)
作者您好，我在MOT_20上训练了baseline+your_models，然后运行MOT20的track.sh，最后的结果全是0，这是正常的,吗？下面是我的MOT20_track.sh
![track](https://github.com/chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT/assets/101462306/50d18077-9e7a-46ef-b891-057cc24ecb86)

**Comment by chen-si-jia** [comment]
> ![res](https://private-user-images.githubusercontent.com/101462306/337742571-b19f556b-612c-43da-ba1e-b79c640c325c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MzYyNTUsIm5iZiI6MTcxNzgzNTk1NSwicGF0aCI6Ii8xMDE0NjIzMDYvMzM3NzQyNTcxLWIxOWY1NTZiLTYxMmMtNDNkYS1iYTFlLWI3OWM2NDBjMzI1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwODM5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjVkNzM3M2YwNzAzNzI2MTBjY2M5OGYwOWRhNDEwNmRiYmQ1NWM1NDg0ZjMwNjE4MWNiYjIyZjk1MzRlMmVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1prDp2MwBeOwWt2pw-QzkTHCYqI7wy1AxN35fc2LwNc) 作者您好，我在MOT_20上训练了baseline+your_models，然后运行MOT20的track.sh，最后的结果全是0，这是正常的,吗？下面是我的MOT20_track.sh ![track](https://private-user-images.githubusercontent.com/101462306/337743956-50d18077-9e7a-46ef-b891-057cc24ecb86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MzYyNTUsIm5iZiI6MTcxNzgzNTk1NSwicGF0aCI6Ii8xMDE0NjIzMDYvMzM3NzQzOTU2LTUwZDE4MDc3LTllN2EtNDZlZi1iODkxLTA1N2NjMjRlY2I4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwODM5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjBjOGJjMmQ0NDdlMDI4Y2M5YzgwN2E5MDE3NjExM2VkNjRjMmQ2N2NmNzQ0M2IwYjFjN2U1MTBjMmQ3NmZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5dtcLZXSLvcpc9Oz4F1dW9MuahS_ptbTOVCtQnwDB6E)

这种情况是不正常的。原因是缺乏测试数据集的正确标签（GT），你看看这个图中GT都为0。

**Comment by Lsyccnu** [comment]
![image](https://github.com/chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT/assets/101462306/65bc08de-9666-4fc3-87d4-5aadccb6ab89)
那我是不是需要通过这个代码生成测试集的labels_with_ids，像train集那样？

**Comment by chen-si-jia** [comment]
> ![image](https://private-user-images.githubusercontent.com/101462306/337868833-65bc08de-9666-4fc3-87d4-5aadccb6ab89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NTI0ODEsIm5iZiI6MTcxNzg1MjE4MSwicGF0aCI6Ii8xMDE0NjIzMDYvMzM3ODY4ODMzLTY1YmMwOGRlLTk2NjYtNGZjMy04N2Q0LTVhYWRjY2I2YWI4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxMzA5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTM5ODVkYjk4ZDllMTU3MDA4NDZkNGE2ZmI4MTUxYzM2YzAzMzE5ZWM0OWJiNjgxOTlmNTViZDk1MWJlZGNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B73PMWBSudrksBGB3ZloX8tqGa8yc2TbC12cYrJ0gsY) 那我是不是需要通过这个代码生成测试集的labels_with_ids，像train集那样？

验证集上评测指标，直接使用train文件夹下的gt.txt作为GT；测试集没有GT，需要去官网评测。labels_with_ids不是用来评测的，而用于训练的。

**Comment by chen-si-jia** [comment]
推理的时候，debug看一看gt是否读取正确。

**Comment by Lsyccnu** [comment]
哦哦哦，也就是说其实这个是验证，用的就是训练集的数据和Groud Truth；
然后我刚刚试了试将track脚本的参数改成如下：
![image](https://github.com/chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT/assets/101462306/72dd8287-f760-41d9-9829-74a1d174ea15)
最后成功得到了验证数据：
![image](https://github.com/chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT/assets/101462306/bd60da18-06d9-4a78-9b1f-923d18842790)
是这样子吗？

**Comment by chen-si-jia** [comment]
> 哦哦哦，也就是说其实这个是验证，用的就是训练集的数据和Groud Truth； 然后我刚刚试了试将track脚本的参数改成如下： ![image](https://private-user-images.githubusercontent.com/101462306/337877405-4da8346c-9788-451f-8a0f-609697530cdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NTQwMTEsIm5iZiI6MTcxNzg1MzcxMSwicGF0aCI6Ii8xMDE0NjIzMDYvMzM3ODc3NDA1LTRkYTgzNDZjLTk3ODgtNDUxZi04YTBmLTYwOTY5NzUzMGNkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxMzM1MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWY2ZDZiYWNmOTc0YjU2OWI1YzkwYzk2YjcyZmE2ZjYxZTE3ODAzOTg3YWM4M2Q2Yjg2ZmY2YmM4NTVmMGU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C4RqZXTNVBG-ub545s5FxFk_MCzr1u6nrsY3LGmPnr8)
> 
> 最后成功得到了验证数据： ![image](https://private-user-images.githubusercontent.com/101462306/337877472-e8ab0282-1aa4-4cc6-b0db-44846a59f88c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NTQwMTEsIm5iZiI6MTcxNzg1MzcxMSwicGF0aCI6Ii8xMDE0NjIzMDYvMzM3ODc3NDcyLWU4YWIwMjgyLTFhYTQtNGNjNi1iMGRiLTQ0ODQ2YTU5Zjg4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxMzM1MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTg3M2NkNWNjMWQ3Zjg1ZjEzZjJjMDBiOGQ4MzgzMWJhNmQ3MGJkNTU4NDFjOTUzYWYxMTNmODVlYWMwM2JmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w_xhKswrPEPTfOT76ogiC8o9APMOLj3qt0NPxBvay_M)
> 
> 是这样子吗？

对的。

**Comment by Lsyccnu** [comment]
明白了，谢谢您！！

**Comment by chen-si-jia** [comment]
> 哦哦哦，也就是说其实这个是验证，用的就是训练集的数据和Groud Truth； 然后我刚刚试了试将track脚本的参数改成如下： ![image](https://private-user-images.githubusercontent.com/101462306/337877405-4da8346c-9788-451f-8a0f-609697530cdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NTQwMTEsIm5iZiI6MTcxNzg1MzcxMSwicGF0aCI6Ii8xMDE0NjIzMDYvMzM3ODc3NDA1LTRkYTgzNDZjLTk3ODgtNDUxZi04YTBmLTYwOTY5NzUzMGNkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxMzM1MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWY2ZDZiYWNmOTc0YjU2OWI1YzkwYzk2YjcyZmE2ZjYxZTE3ODAzOTg3YWM4M2Q2Yjg2ZmY2YmM4NTVmMGU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C4RqZXTNVBG-ub545s5FxFk_MCzr1u6nrsY3LGmPnr8)
> 
> 最后成功得到了验证数据： ![image](https://private-user-images.githubusercontent.com/101462306/337877472-e8ab0282-1aa4-4cc6-b0db-44846a59f88c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NTQwMTEsIm5iZiI6MTcxNzg1MzcxMSwicGF0aCI6Ii8xMDE0NjIzMDYvMzM3ODc3NDcyLWU4YWIwMjgyLTFhYTQtNGNjNi1iMGRiLTQ0ODQ2YTU5Zjg4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxMzM1MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTg3M2NkNWNjMWQ3Zjg1ZjEzZjJjMDBiOGQ4MzgzMWJhNmQ3MGJkNTU4NDFjOTUzYWYxMTNmODVlYWMwM2JmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w_xhKswrPEPTfOT76ogiC8o9APMOLj3qt0NPxBvay_M)
> 
> 是这样子吗？

val_mot20是直接在验证集评测，由于验证集本地是有GT的，所以会直接出指标。test_mot20是在测试集评测，看起来得到的指标都是0，但这个结果是不正确的，需要将评测生成的结果传到MOTChanglle官网，就可以得到正确的指标了。

**Comment by Lsyccnu** [comment]
那这个在test_mot20上生成的评测结果，是上传的summary——MOT20.xlsx这个结果文件吗（如下图）？还是其他文件呢？
![image](https://github.com/chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT/assets/101462306/19d5f9ac-6f69-47f5-92e4-da3ceb52e0bd)

**Comment by chen-si-jia** [comment]
> 那这个在test_mot20上生成的评测结果，是上传的summary——MOT20.xlsx这个结果文件吗（如下图）？还是其他文件呢？ ![image](https://private-user-images.githubusercontent.com/101462306/337880821-19d5f9ac-6f69-47f5-92e4-da3ceb52e0bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NTczMzQsIm5iZiI6MTcxNzg1NzAzNCwicGF0aCI6Ii8xMDE0NjIzMDYvMzM3ODgwODIxLTE5ZDVmOWFjLTZmNjktNDdmNS05MmU0LWRhM2NlYjUyZTBiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxNDMwMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDVhMGJiNDgwYjhkMWZlOGFkZTdiZjA3MzVmOTFhMmRmYWQ4MWNmZTg4NjBlODhjNTZmM2QwMmM5ZjAwNTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uaz8FQPrij24XExOmA1G2i9bYfBmb-9auOQWFE5PNDU)

将推理得到的txt文件，压缩成results.zip上传到评测的地方即可，具体参考MOTChanglle网站的提交说明。

**Comment by Lsyccnu** [comment]
好的
